### ISSUE TITLE
[Chore] 更新README中的时间信息

### ISSUE THREAD

**Issue by tyn1998** [ECNU/OpenSODA#7]
OpenSODA为了配合开放原子的宣发节点进行了[整体日期的调整](https://xlab2017.yuque.com/staff-kbz9wp/olpzth/tyyu5od84vxsi69l)，因此本仓库[README](https://github.com/ECNU/OpenSODA/blob/main/README.md)中的一些时间信息已经失去时效性，需要调整（@will-ww 王老师推荐用Markdown删除线保留原日期）：

<table>
<tr>
 <td><img width="1057" alt="image" src="https://github.com/ECNU/OpenSODA/assets/32434520/369acb49-98d1-4578-bb20-efa37fb3a9a9">
 <td><img width="608" alt="image" src="https://github.com/ECNU/OpenSODA/assets/32434520/71fa0c1f-c4ed-4d60-b7ad-16b15f8d19d4">
 <td><img width="1014" alt="image" src="https://github.com/ECNU/OpenSODA/assets/32434520/01b98ae7-98cd-4c87-adb2-48dc976100dd">
</table>

Hello @zzzz-niu，你愿意帮忙修改一下吗？如果你愿意的话，请先Fork该仓库，然后在你的Fork仓库中新建一个Git分支进行修改，修改后向本仓库的main分支提一个PR，我会来review你的PR。

虽然不涉及代码，但你也会经历一个精简版的GitHub/Git协作流程。一些参考：

- https://www.yuque.com/tyn1998/blogs/exot72 (图中不是所有流程在这个任务中都会涉及到)
- https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md （在Hypercrx中我们是这么来协作的）
- 自行搜索（搜索能力是核心技能）
- 还有拿不准的请在该issue下留言提问

**Comment by HalloMelon** [comment]
Of course! Thanks for your invitation~
